stages:
  - setup
  - lint
  - madge
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

setup_dependencies:
  stage: setup
  image: node:latest
  script:
    - echo "Installing dependencies..."
    - npm install
  only:
    - merge_requests

lint_job:
  stage: lint
  image: node:latest
  script:
    - echo "Running linting..."
    - npm run lint
  only:
    - merge_requests

test_job:
  stage: test
  image: node:latest
  script:
    - echo "Running tests..."
    - npm test
  only:
    - merge_requests

madge_job:
  stage: madge
  image: node:latest
  script:
    - echo "Checking circular dependencies. Running madge..."
    - npm run madge
  only:
    - merge_requests